import AccountIcon from './account.svg';
import BackIcon from './back.svg';
import CircularProgress from './circularprogress.svg';
import AddToPlaylistIcon from './addtoplaylist.svg';
import RemoveFromPlaylistIcon from './removefromplaylist.svg';
import PlayIcon from './play.svg';
import PlaylistIcon from './playlist.svg';
import ProfileIcon from './profile.svg';
import UserIcon from "./user.svg";
import SkipIcon from "./skip.svg";
import PauseIcon from "./pause.svg";
import VolumeUpIcon from "./volumeup.svg";
import VolumeDownIcon from "./volumedown.svg";
import DeletePlaylistIcon from "./deleteplaylist.svg";
import WebLogo from "./webplayer.svg";
import PersonIcon from "./person.svg";
import SearchIcon from "./search.svg";
export { AccountIcon, BackIcon, CircularProgress, AddToPlaylistIcon, RemoveFromPlaylistIcon, PlayIcon, PlaylistIcon, ProfileIcon, UserIcon, SkipIcon, PauseIcon, VolumeUpIcon, VolumeDownIcon, DeletePlaylistIcon, WebLogo, PersonIcon, SearchIcon };